# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 276facc4eaef615dffa34bf4105421de878a0f7e0244181a994af5fd2abab78f9ebb26f9a4c716187f798d8bf5a4d2e2fba1f81bd2be8e3ee62be51d9552a8e2

test:
  secret_key_base: 0b3feb36320fa5b33ab3a559b4956bca10b9e902e58251fbdddc3e0bf1ac3c6f50248c7f73ad037d0be373b3ccb3e95a544920746da9f83f5c4b1bf75e3f833b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
